# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

desc "Deploy a new version to the Google Play"
lane :internal do

Dir.chdir ".." do
  sh("flutter", "packages", "get")
  sh("flutter", "clean")
  sh("flutter", "build", "appbundle")
end

upload_to_play_store(
aab: "/home/circleci/project/build/app/outputs/bundle/release/app-release.aab",
release_status: 'draft',
track: "internal",
json_key: "/home/circleci/project/android/google_play_json_key.json"
)
end


default_platform(:android)

desc "Deploy a new version to firebase"
lane :staging do

Dir.chdir ".." do
  sh("flutter", "packages", "get")
  sh("flutter", "clean")
  sh("flutter", "build", "appbundle")
end

firebase_app_distribution(
    app: "1:760140056434:android:6ef2f6d8684c35d6ebbfeb",
    groups: "emem",
    release_notes: "new features",
    android_artifact_path: "/home/circleci/project/build/app/outputs/apk/release/app-release.apk",
    android_artifact_type: "APK",
	  firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
)
end
