name: Deploy
on:
  pull_request:
    branches:
      - main

jobs:
  flutter_build:
    name: Build appbundle
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.2'
  
    - name: Create env file
          run: |
            touch .env
            echo PAYSTACK_PK=${{ secrets.PAYSTACK_PK }} >> .env
            echo PAYSTACK_SK=${{ secret.PAYSTACK_SK }} >> .env
            echo GOOGLE_API=${{ secret.GOOGLE_API }} >> .env
            cat .env

    - run: flutter pub get
    - run: flutter build appbundle
  
    - name:  Notify Slacks
      if: ${{ always() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: 'Application build ${{ job.status }}'
        SLACK_TITLE: Build ${{ job.status }}
  # deploy_to_playstore:
  #   name: Deploy to Playstore
  #   needs: flutter_build

  # deploy_to_playstore:
  #   name: Deploy to Playstore
  #   needs: flutter_build
